// SPDX-License-Identifier: MIT
// Copyright (c) 2026 AgentEval Contributors
// Licensed under the MIT License.

using System.Globalization;
using System.Text;

namespace AgentEval.Comparison;

/// <summary>
/// Extension methods for exporting model comparison results to Markdown format.
/// </summary>
/// <remarks>
/// Provides rich, human-readable Markdown output for model comparisons,
/// suitable for documentation, GitHub comments, or CI/CD reports.
/// </remarks>
public static class ModelComparisonExtensions
{
    /// <summary>
    /// Converts a single model comparison result to a complete Markdown report.
    /// </summary>
    /// <param name="result">The comparison result to export.</param>
    /// <param name="options">Optional formatting options.</param>
    /// <returns>A formatted Markdown string.</returns>
    public static string ToMarkdown(this ModelComparisonResult result, MarkdownExportOptions? options = null)
    {
        options ??= MarkdownExportOptions.Default;
        var sb = new StringBuilder();

        // Header
        if (options.IncludeHeader)
        {
            sb.AppendLine($"# {options.HeaderEmoji} Model Comparison Report");
            sb.AppendLine();
            sb.AppendLine($"**Test Case:** {result.TestCase.Name}");
            sb.AppendLine($"**Input:** `{result.TestCase.Input}`");
            sb.AppendLine($"**Models Compared:** {result.ModelResults.Count}");
            sb.AppendLine($"**Runs Per Model:** {result.Options.RunsPerModel}");
            sb.AppendLine();
        }

        // Winner announcement
        if (options.IncludeWinnerAnnouncement)
        {
            sb.AppendLine("## 🏆 Winner");
            sb.AppendLine();
            sb.AppendLine($"> **{result.Winner.ModelName}** achieved the highest composite score of **{result.Winner.CompositeScore:F1}**");
            sb.AppendLine();
        }

        // Rankings table
        if (options.IncludeRankingsTable)
        {
            sb.AppendLine("## 📊 Rankings");
            sb.AppendLine();
            sb.AppendLine(result.ToRankingsTable(options));
            sb.AppendLine();
        }

        // Detailed metrics
        if (options.IncludeDetailedMetrics)
        {
            sb.AppendLine("## 📈 Detailed Metrics");
            sb.AppendLine();
            sb.AppendLine(result.ToDetailedMetricsTable(options));
            sb.AppendLine();
        }

        // Statistical analysis
        if (options.IncludeStatistics)
        {
            sb.AppendLine("## 📉 Statistical Analysis");
            sb.AppendLine();
            sb.AppendLine(result.ToStatisticsTable(options));
            sb.AppendLine();
        }

        // Scoring weights used
        if (options.IncludeScoringWeights)
        {
            sb.AppendLine("## ⚖️ Scoring Weights");
            sb.AppendLine();
            var weights = result.Options.EffectiveScoringWeights;
            sb.AppendLine($"| Dimension | Weight |");
            sb.AppendLine($"|-----------|--------|");
            sb.AppendLine($"| Quality | {weights.Quality:P0} |");
            sb.AppendLine($"| Speed | {weights.Speed:P0} |");
            sb.AppendLine($"| Cost | {weights.Cost:P0} |");
            sb.AppendLine($"| Reliability | {weights.Reliability:P0} |");
            sb.AppendLine();
        }

        // Footer with timestamp
        if (options.IncludeTimestamp)
        {
            sb.AppendLine("---");
            sb.AppendLine($"*Generated by AgentEval on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC*");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Converts multiple comparison results to a comprehensive Markdown report.
    /// </summary>
    /// <param name="results">The comparison results to export.</param>
    /// <param name="options">Optional formatting options.</param>
    /// <returns>A formatted Markdown string with all results.</returns>
    public static string ToMarkdown(this IReadOnlyList<ModelComparisonResult> results, MarkdownExportOptions? options = null)
    {
        if (results.Count == 0)
            return "No comparison results to display.";

        options ??= MarkdownExportOptions.Default;
        var sb = new StringBuilder();

        // Main header
        sb.AppendLine($"# {options.HeaderEmoji} Model Comparison Report");
        sb.AppendLine();
        sb.AppendLine($"**Total Test Cases:** {results.Count}");
        sb.AppendLine($"**Models Compared:** {results[0].ModelResults.Count}");
        sb.AppendLine();

        // Summary table showing wins per model
        sb.AppendLine("## 🥇 Overall Win Summary");
        sb.AppendLine();
        sb.AppendLine(GenerateWinSummaryTable(results));
        sb.AppendLine();

        // Aggregate rankings across all tests
        sb.AppendLine("## 📊 Aggregate Rankings");
        sb.AppendLine();
        sb.AppendLine(GenerateAggregateRankingsTable(results, options));
        sb.AppendLine();

        // Individual test case results
        sb.AppendLine("## 📝 Individual Test Results");
        sb.AppendLine();

        for (int i = 0; i < results.Count; i++)
        {
            var result = results[i];
            sb.AppendLine($"### Test {i + 1}: {result.TestCase.Name}");
            sb.AppendLine();
            sb.AppendLine($"**Input:** `{result.TestCase.Input}`");
            sb.AppendLine($"**Winner:** {GetMedalEmoji(1)} {result.Winner.ModelName} ({result.Winner.CompositeScore:F1})");
            sb.AppendLine();
            sb.AppendLine(result.ToRankingsTable(options));
            sb.AppendLine();
        }

        // Footer
        if (options.IncludeTimestamp)
        {
            sb.AppendLine("---");
            sb.AppendLine($"*Generated by AgentEval on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC*");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a compact rankings table for a single comparison result.
    /// </summary>
    /// <param name="result">The comparison result.</param>
    /// <param name="options">Optional formatting options.</param>
    /// <returns>A Markdown table string.</returns>
    public static string ToRankingsTable(this ModelComparisonResult result, MarkdownExportOptions? options = null)
    {
        options ??= MarkdownExportOptions.Default;
        var sb = new StringBuilder();

        sb.AppendLine("| Rank | Model | Composite | Quality | Speed | Cost | Reliability |");
        sb.AppendLine("|------|-------|-----------|---------|-------|------|-------------|");

        foreach (var ranking in result.Ranking)
        {
            var medal = GetMedalEmoji(ranking.Rank);
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "| {0} {1} | {2} | **{3:F1}** | {4:F1} | {5:F1} | {6:F1} | {7:F1} |",
                medal,
                ranking.Rank,
                ranking.ModelName,
                ranking.CompositeScore,
                ranking.QualityScore,
                ranking.SpeedScore,
                ranking.CostScore,
                ranking.ReliabilityScore));
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a detailed metrics table showing raw performance data.
    /// </summary>
    /// <param name="result">The comparison result.</param>
    /// <param name="options">Optional formatting options.</param>
    /// <returns>A Markdown table string.</returns>
    public static string ToDetailedMetricsTable(this ModelComparisonResult result, MarkdownExportOptions? options = null)
    {
        options ??= MarkdownExportOptions.Default;
        var sb = new StringBuilder();

        sb.AppendLine("| Model | Pass Rate | Mean Score | Avg Latency | Avg Cost | Total Cost |");
        sb.AppendLine("|-------|-----------|------------|-------------|----------|------------|");

        foreach (var modelResult in result.ModelResults.OrderByDescending(m => m.PassRate))
        {
            var passRateFormatted = $"{modelResult.PassRate:P1}";
            var meanScoreFormatted = $"{modelResult.MeanScore:F1}";
            var latencyFormatted = FormatDuration(modelResult.AverageLatency);
            var avgCostFormatted = modelResult.AverageCost.HasValue 
                ? $"${modelResult.AverageCost:F4}" 
                : "N/A";
            var totalCostFormatted = modelResult.TotalCost.HasValue 
                ? $"${modelResult.TotalCost:F4}" 
                : "N/A";

            sb.AppendLine($"| {modelResult.ModelName} | {passRateFormatted} | {meanScoreFormatted} | {latencyFormatted} | {avgCostFormatted} | {totalCostFormatted} |");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a statistics table showing distribution metrics.
    /// </summary>
    /// <param name="result">The comparison result.</param>
    /// <param name="options">Optional formatting options.</param>
    /// <returns>A Markdown table string.</returns>
    public static string ToStatisticsTable(this ModelComparisonResult result, MarkdownExportOptions? options = null)
    {
        options ??= MarkdownExportOptions.Default;
        var sb = new StringBuilder();

        sb.AppendLine("| Model | Mean | Median | Std Dev | Min | Max | P25 | P75 | P95 |");
        sb.AppendLine("|-------|------|--------|---------|-----|-----|-----|-----|-----|");

        foreach (var modelResult in result.ModelResults.OrderByDescending(m => m.MeanScore))
        {
            var stats = modelResult.StochasticResult.Statistics;
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "| {0} | {1:F1} | {2:F1} | {3:F2} | {4} | {5} | {6:F1} | {7:F1} | {8:F1} |",
                modelResult.ModelName,
                stats.MeanScore,
                stats.MedianScore,
                stats.StandardDeviation,
                stats.MinScore,
                stats.MaxScore,
                stats.Percentile25,
                stats.Percentile75,
                stats.Percentile95));
        }

        // Add confidence intervals if available
        var hasConfidenceIntervals = result.ModelResults.Any(m => 
            m.StochasticResult.Statistics.ConfidenceInterval != null);

        if (hasConfidenceIntervals)
        {
            sb.AppendLine();
            sb.AppendLine("**Confidence Intervals:**");
            sb.AppendLine();

            foreach (var modelResult in result.ModelResults)
            {
                var ci = modelResult.StochasticResult.Statistics.ConfidenceInterval;
                if (ci != null)
                {
                    sb.AppendLine($"- **{modelResult.ModelName}**: {ci}");
                }
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a Markdown summary suitable for GitHub PR comments.
    /// </summary>
    /// <param name="result">The comparison result.</param>
    /// <returns>A compact Markdown summary.</returns>
    public static string ToGitHubComment(this ModelComparisonResult result)
    {
        var sb = new StringBuilder();

        sb.AppendLine("### 🤖 Model Comparison Results");
        sb.AppendLine();
        sb.AppendLine($"**Test:** {result.TestCase.Name}");
        sb.AppendLine($"**Winner:** 🏆 {result.Winner.ModelName} (Score: {result.Winner.CompositeScore:F1})");
        sb.AppendLine();
        sb.AppendLine("<details>");
        sb.AppendLine("<summary>View full rankings</summary>");
        sb.AppendLine();
        sb.AppendLine(result.ToRankingsTable());
        sb.AppendLine();
        sb.AppendLine("</details>");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a multi-result summary suitable for GitHub PR comments.
    /// </summary>
    /// <param name="results">The comparison results.</param>
    /// <returns>A compact Markdown summary.</returns>
    public static string ToGitHubComment(this IReadOnlyList<ModelComparisonResult> results)
    {
        if (results.Count == 0)
            return "No comparison results to display.";

        var sb = new StringBuilder();

        sb.AppendLine("### 🤖 Model Comparison Summary");
        sb.AppendLine();

        // Count wins per model
        var winCounts = results
            .GroupBy(r => r.Winner.ModelName)
            .Select(g => (Model: g.Key, Wins: g.Count()))
            .OrderByDescending(x => x.Wins)
            .ToList();

        sb.AppendLine("**Win Distribution:**");
        foreach (var (model, wins) in winCounts)
        {
            var bar = new string('█', wins);
            sb.AppendLine($"- {model}: {bar} ({wins}/{results.Count})");
        }

        sb.AppendLine();
        sb.AppendLine("<details>");
        sb.AppendLine("<summary>View all test results</summary>");
        sb.AppendLine();

        foreach (var result in results)
        {
            sb.AppendLine($"- **{result.TestCase.Name}**: 🏆 {result.Winner.ModelName} ({result.Winner.CompositeScore:F1})");
        }

        sb.AppendLine();
        sb.AppendLine("</details>");

        return sb.ToString();
    }

    /// <summary>
    /// Saves the comparison result to a Markdown file.
    /// </summary>
    /// <param name="result">The comparison result.</param>
    /// <param name="filePath">The path to save the file.</param>
    /// <param name="options">Optional formatting options.</param>
    public static async Task SaveToMarkdownAsync(
        this ModelComparisonResult result, 
        string filePath, 
        MarkdownExportOptions? options = null)
    {
        var markdown = result.ToMarkdown(options);
        await File.WriteAllTextAsync(filePath, markdown);
    }

    /// <summary>
    /// Saves multiple comparison results to a Markdown file.
    /// </summary>
    /// <param name="results">The comparison results.</param>
    /// <param name="filePath">The path to save the file.</param>
    /// <param name="options">Optional formatting options.</param>
    public static async Task SaveToMarkdownAsync(
        this IReadOnlyList<ModelComparisonResult> results, 
        string filePath, 
        MarkdownExportOptions? options = null)
    {
        var markdown = results.ToMarkdown(options);
        await File.WriteAllTextAsync(filePath, markdown);
    }

    private static string GenerateWinSummaryTable(IReadOnlyList<ModelComparisonResult> results)
    {
        var winCounts = results
            .GroupBy(r => r.Winner.ModelName)
            .Select(g => (Model: g.Key, Wins: g.Count(), WinRate: (double)g.Count() / results.Count))
            .OrderByDescending(x => x.Wins)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("| Model | Wins | Win Rate |");
        sb.AppendLine("|-------|------|----------|");

        foreach (var (model, wins, winRate) in winCounts)
        {
            var medal = wins == winCounts.Max(w => w.Wins) ? "🏆 " : "";
            sb.AppendLine($"| {medal}{model} | {wins}/{results.Count} | {winRate:P0} |");
        }

        return sb.ToString();
    }

    private static string GenerateAggregateRankingsTable(
        IReadOnlyList<ModelComparisonResult> results,
        MarkdownExportOptions options)
    {
        // Calculate average scores across all tests
        var modelScores = results
            .SelectMany(r => r.Ranking)
            .GroupBy(r => r.ModelName)
            .Select(g => new
            {
                ModelName = g.Key,
                AvgComposite = g.Average(r => r.CompositeScore),
                AvgQuality = g.Average(r => r.QualityScore),
                AvgSpeed = g.Average(r => r.SpeedScore),
                AvgCost = g.Average(r => r.CostScore),
                AvgReliability = g.Average(r => r.ReliabilityScore),
                AvgRank = g.Average(r => r.Rank)
            })
            .OrderByDescending(m => m.AvgComposite)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("| Rank | Model | Avg Composite | Avg Quality | Avg Speed | Avg Cost | Avg Reliability | Avg Rank |");
        sb.AppendLine("|------|-------|---------------|-------------|-----------|----------|-----------------|----------|");

        int rank = 1;
        foreach (var model in modelScores)
        {
            var medal = GetMedalEmoji(rank);
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "| {0} {1} | {2} | **{3:F1}** | {4:F1} | {5:F1} | {6:F1} | {7:F1} | {8:F2} |",
                medal,
                rank,
                model.ModelName,
                model.AvgComposite,
                model.AvgQuality,
                model.AvgSpeed,
                model.AvgCost,
                model.AvgReliability,
                model.AvgRank));
            rank++;
        }

        return sb.ToString();
    }

    private static string GetMedalEmoji(int rank) => rank switch
    {
        1 => "🥇",
        2 => "🥈",
        3 => "🥉",
        _ => $"#{rank}"
    };

    private static string FormatDuration(TimeSpan duration)
    {
        if (duration.TotalMilliseconds < 1000)
            return $"{duration.TotalMilliseconds:F0}ms";
        if (duration.TotalSeconds < 60)
            return $"{duration.TotalSeconds:F2}s";
        return $"{duration.TotalMinutes:F1}min";
    }
}

/// <summary>
/// Options for customizing Markdown export output.
/// </summary>
public class MarkdownExportOptions
{
    /// <summary>
    /// Default export options with all sections enabled.
    /// </summary>
    public static MarkdownExportOptions Default { get; } = new();

    /// <summary>
    /// Minimal export options with only essential sections.
    /// </summary>
    public static MarkdownExportOptions Minimal { get; } = new()
    {
        IncludeDetailedMetrics = false,
        IncludeStatistics = false,
        IncludeScoringWeights = false,
        IncludeTimestamp = false
    };

    /// <summary>
    /// Whether to include the header section.
    /// </summary>
    public bool IncludeHeader { get; init; } = true;

    /// <summary>
    /// Whether to include the winner announcement.
    /// </summary>
    public bool IncludeWinnerAnnouncement { get; init; } = true;

    /// <summary>
    /// Whether to include the rankings table.
    /// </summary>
    public bool IncludeRankingsTable { get; init; } = true;

    /// <summary>
    /// Whether to include detailed metrics (pass rate, latency, cost).
    /// </summary>
    public bool IncludeDetailedMetrics { get; init; } = true;

    /// <summary>
    /// Whether to include statistical analysis (mean, median, percentiles).
    /// </summary>
    public bool IncludeStatistics { get; init; } = true;

    /// <summary>
    /// Whether to include the scoring weights section.
    /// </summary>
    public bool IncludeScoringWeights { get; init; } = true;

    /// <summary>
    /// Whether to include a timestamp footer.
    /// </summary>
    public bool IncludeTimestamp { get; init; } = true;

    /// <summary>
    /// Emoji to use in the header.
    /// </summary>
    public string HeaderEmoji { get; init; } = "🔬";

    /// <summary>
    /// Number of decimal places for scores.
    /// </summary>
    public int ScoreDecimalPlaces { get; init; } = 1;
}
