// Copyright (c) 2025-2026 AgentEval Contributors
// Licensed under the MIT License.

using AgentEval.Comparison;
using AgentEval.Models;
using Xunit;

namespace AgentEval.Tests.Comparison;

/// <summary>
/// Unit tests for ModelComparisonExtensions (Markdown export).
/// </summary>
public class ModelComparisonExtensionsTests
{
    #region ToMarkdown Tests
    
    [Fact]
    public void ToMarkdown_SingleResult_IncludesAllSections()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var markdown = result.ToMarkdown();
        
        // Assert
        Assert.Contains("# 🔬 Model Comparison Report", markdown);
        Assert.Contains("## 🏆 Winner", markdown);
        Assert.Contains("## 📊 Rankings", markdown);
        Assert.Contains("## 📈 Detailed Metrics", markdown);
        Assert.Contains("## 📉 Statistical Analysis", markdown);
        Assert.Contains("## ⚖️ Scoring Weights", markdown);
        Assert.Contains("Generated by AgentEval", markdown);
    }
    
    [Fact]
    public void ToMarkdown_SingleResult_ContainsWinnerInfo()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var markdown = result.ToMarkdown();
        
        // Assert
        Assert.Contains("**GPT-4o**", markdown); // Winner model name
        Assert.Contains("highest composite score", markdown);
    }
    
    [Fact]
    public void ToMarkdown_WithMinimalOptions_ExcludesOptionalSections()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        var options = MarkdownExportOptions.Minimal;
        
        // Act
        var markdown = result.ToMarkdown(options);
        
        // Assert
        Assert.Contains("Rankings", markdown);
        Assert.DoesNotContain("Detailed Metrics", markdown);
        Assert.DoesNotContain("Statistical Analysis", markdown);
        Assert.DoesNotContain("Scoring Weights", markdown);
        Assert.DoesNotContain("Generated by AgentEval", markdown);
    }
    
    [Fact]
    public void ToMarkdown_CustomOptions_RespectsSettings()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        var options = new MarkdownExportOptions
        {
            IncludeHeader = true,
            IncludeWinnerAnnouncement = false,
            IncludeRankingsTable = true,
            IncludeDetailedMetrics = false,
            IncludeStatistics = false,
            IncludeScoringWeights = false,
            IncludeTimestamp = false,
            HeaderEmoji = "🧪"
        };
        
        // Act
        var markdown = result.ToMarkdown(options);
        
        // Assert
        Assert.Contains("🧪", markdown);
        Assert.DoesNotContain("Winner", markdown);
        Assert.Contains("Rankings", markdown);
    }
    
    #endregion
    
    #region ToRankingsTable Tests
    
    [Fact]
    public void ToRankingsTable_GeneratesValidMarkdownTable()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var table = result.ToRankingsTable();
        
        // Assert
        Assert.Contains("| Rank | Model | Composite | Quality | Speed | Cost | Reliability |", table);
        Assert.Contains("|------|-------|-----------|---------|-------|------|-------------|", table);
        Assert.Contains("🥇", table); // First place medal
        Assert.Contains("🥈", table); // Second place medal
    }
    
    [Fact]
    public void ToRankingsTable_OrdersModelsCorrectly()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var table = result.ToRankingsTable();
        var lines = table.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        
        // Assert - verify table has header + separator + 2 model rows
        Assert.True(lines.Length >= 4);
        
        // First model row should have gold medal
        Assert.Contains("🥇", lines[2]);
        
        // Second model row should have silver medal
        Assert.Contains("🥈", lines[3]);
    }
    
    #endregion
    
    #region ToDetailedMetricsTable Tests
    
    [Fact]
    public void ToDetailedMetricsTable_IncludesAllColumns()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var table = result.ToDetailedMetricsTable();
        
        // Assert
        Assert.Contains("Model", table);
        Assert.Contains("Pass Rate", table);
        Assert.Contains("Mean Score", table);
        Assert.Contains("Avg Latency", table);
        Assert.Contains("Avg Cost", table);
        Assert.Contains("Total Cost", table);
    }
    
    [Fact]
    public void ToDetailedMetricsTable_FormatsValuesCorrectly()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var table = result.ToDetailedMetricsTable();
        
        // Assert
        Assert.Contains("%", table); // Pass rate percentage
        Assert.Contains("ms", table); // Duration in milliseconds
    }
    
    #endregion
    
    #region ToStatisticsTable Tests
    
    [Fact]
    public void ToStatisticsTable_IncludesPercentiles()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var table = result.ToStatisticsTable();
        
        // Assert
        Assert.Contains("Mean", table);
        Assert.Contains("Median", table);
        Assert.Contains("Std Dev", table);
        Assert.Contains("Min", table);
        Assert.Contains("Max", table);
        Assert.Contains("P25", table);
        Assert.Contains("P75", table);
        Assert.Contains("P95", table);
    }
    
    #endregion
    
    #region ToGitHubComment Tests
    
    [Fact]
    public void ToGitHubComment_SingleResult_IncludesCollapsibleSection()
    {
        // Arrange
        var result = CreateSampleComparisonResult();
        
        // Act
        var comment = result.ToGitHubComment();
        
        // Assert
        Assert.Contains("### 🤖 Model Comparison Results", comment);
        Assert.Contains("<details>", comment);
        Assert.Contains("<summary>View full rankings</summary>", comment);
        Assert.Contains("</details>", comment);
        Assert.Contains("Winner:", comment);
        Assert.Contains("🏆", comment);
    }
    
    [Fact]
    public void ToGitHubComment_MultipleResults_ShowsWinDistribution()
    {
        // Arrange
        var results = new List<ModelComparisonResult>
        {
            CreateSampleComparisonResult("Test 1"),
            CreateSampleComparisonResult("Test 2"),
            CreateSampleComparisonResult("Test 3")
        };
        
        // Act
        var comment = results.ToGitHubComment();
        
        // Assert
        Assert.Contains("Model Comparison Summary", comment);
        Assert.Contains("Win Distribution", comment);
        Assert.Contains("█", comment); // Bar chart character
        Assert.Contains("<details>", comment);
    }
    
    [Fact]
    public void ToGitHubComment_EmptyResults_ReturnsMessage()
    {
        // Arrange
        var results = new List<ModelComparisonResult>();
        
        // Act
        var comment = results.ToGitHubComment();
        
        // Assert
        Assert.Contains("No comparison results", comment);
    }
    
    #endregion
    
    #region Multiple Results Tests
    
    [Fact]
    public void ToMarkdown_MultipleResults_IncludesAggregateSummary()
    {
        // Arrange
        var results = new List<ModelComparisonResult>
        {
            CreateSampleComparisonResult("Test Case 1"),
            CreateSampleComparisonResult("Test Case 2")
        };
        
        // Act
        var markdown = results.ToMarkdown();
        
        // Assert
        Assert.Contains("# 🔬 Model Comparison Report", markdown);
        Assert.Contains("Overall Win Summary", markdown);
        Assert.Contains("Aggregate Rankings", markdown);
        Assert.Contains("Individual Test Results", markdown);
        Assert.Contains("Test Case 1", markdown);
        Assert.Contains("Test Case 2", markdown);
    }
    
    [Fact]
    public void ToMarkdown_MultipleResults_EmptyList_ReturnsMessage()
    {
        // Arrange
        var results = new List<ModelComparisonResult>();
        
        // Act
        var markdown = results.ToMarkdown();
        
        // Assert
        Assert.Contains("No comparison results", markdown);
    }
    
    #endregion
    
    #region MarkdownExportOptions Tests
    
    [Fact]
    public void MarkdownExportOptions_Default_HasAllOptionsEnabled()
    {
        // Act
        var options = MarkdownExportOptions.Default;
        
        // Assert
        Assert.True(options.IncludeHeader);
        Assert.True(options.IncludeWinnerAnnouncement);
        Assert.True(options.IncludeRankingsTable);
        Assert.True(options.IncludeDetailedMetrics);
        Assert.True(options.IncludeStatistics);
        Assert.True(options.IncludeScoringWeights);
        Assert.True(options.IncludeTimestamp);
        Assert.Equal("🔬", options.HeaderEmoji);
    }
    
    [Fact]
    public void MarkdownExportOptions_Minimal_HasReducedOptions()
    {
        // Act
        var options = MarkdownExportOptions.Minimal;
        
        // Assert
        Assert.True(options.IncludeHeader);
        Assert.True(options.IncludeWinnerAnnouncement);
        Assert.True(options.IncludeRankingsTable);
        Assert.False(options.IncludeDetailedMetrics);
        Assert.False(options.IncludeStatistics);
        Assert.False(options.IncludeScoringWeights);
        Assert.False(options.IncludeTimestamp);
    }
    
    #endregion
    
    #region Helper Methods
    
    private static ModelComparisonResult CreateSampleComparisonResult(string testName = "Sample Test")
    {
        var testCase = new TestCase
        {
            Name = testName,
            Input = "What is 2+2?",
            GroundTruth = "4"
        };
        
        var stats1 = new StochasticStatistics(
            PassRate: 0.95,
            MeanScore: 92.5,
            MedianScore: 94.0,
            StandardDeviation: 3.2,
            MinScore: 85,
            MaxScore: 100,
            Percentile25: 90.0,
            Percentile75: 96.0,
            Percentile95: 99.0,
            ConfidenceInterval: new ConfidenceInterval(90.5, 94.5, 0.95),
            SampleSize: 10);
        
        var stats2 = new StochasticStatistics(
            PassRate: 0.85,
            MeanScore: 85.0,
            MedianScore: 86.0,
            StandardDeviation: 5.5,
            MinScore: 72,
            MaxScore: 95,
            Percentile25: 80.0,
            Percentile75: 90.0,
            Percentile95: 94.0,
            ConfidenceInterval: new ConfidenceInterval(82.0, 88.0, 0.95),
            SampleSize: 10);
        
        var stochasticResult1 = new StochasticResult(
            TestCase: testCase,
            IndividualResults: CreateSampleTestResults(10),
            Statistics: stats1,
            Options: new StochasticOptions(Runs: 10),
            Passed: true);
        
        var stochasticResult2 = new StochasticResult(
            TestCase: testCase,
            IndividualResults: CreateSampleTestResults(10),
            Statistics: stats2,
            Options: new StochasticOptions(Runs: 10),
            Passed: true);
        
        var modelResults = new List<ModelResult>
        {
            new ModelResult(
                ModelId: "gpt-4o",
                ModelName: "GPT-4o",
                StochasticResult: stochasticResult1,
                AverageLatency: TimeSpan.FromMilliseconds(250),
                AverageCost: 0.0025m,
                TotalCost: 0.025m),
            new ModelResult(
                ModelId: "gpt-4o-mini",
                ModelName: "GPT-4o-mini",
                StochasticResult: stochasticResult2,
                AverageLatency: TimeSpan.FromMilliseconds(150),
                AverageCost: 0.0005m,
                TotalCost: 0.005m)
        };
        
        var rankings = new List<ModelRanking>
        {
            new ModelRanking(
                ModelId: "gpt-4o",
                ModelName: "GPT-4o",
                CompositeScore: 88.5,
                QualityScore: 95.0,
                SpeedScore: 70.0,
                CostScore: 60.0,
                ReliabilityScore: 95.0,
                Rank: 1),
            new ModelRanking(
                ModelId: "gpt-4o-mini",
                ModelName: "GPT-4o-mini",
                CompositeScore: 82.0,
                QualityScore: 80.0,
                SpeedScore: 90.0,
                CostScore: 95.0,
                ReliabilityScore: 85.0,
                Rank: 2)
        };
        
        var options = new ModelComparisonOptions
        {
            RunsPerModel = 10,
            EnableCostAnalysis = true,
            EnableStatistics = true
        };
        
        return new ModelComparisonResult(
            TestCase: testCase,
            ModelResults: modelResults,
            Ranking: rankings,
            Winner: rankings[0],
            Options: options);
    }
    
    private static IReadOnlyList<TestResult> CreateSampleTestResults(int count)
    {
        var results = new List<TestResult>();
        for (int i = 0; i < count; i++)
        {
            var perf = new PerformanceMetrics
            {
                StartTime = DateTimeOffset.UtcNow,
                PromptTokens = 50,
                CompletionTokens = 10,
                ModelUsed = "gpt-4o"
            };
            perf.EndTime = perf.StartTime + TimeSpan.FromMilliseconds(200 + i * 10);
            
            results.Add(new TestResult
            {
                TestName = $"Test_{i}",
                Passed = i < count - 1, // Last one fails for variety
                ActualOutput = "4",
                Performance = perf
            });
        }
        return results;
    }
    
    #endregion
}
